server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      fail-fast: true

      server:
        git:
          uri: git@bitbucket.org:TarekSaid/blotit-config.git
          clone-on-start: true

      discovery:
        enabled: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: test

eureka:
  client:
    enabled: false